### ISSUE TITLE
v31 branch won't build on Python 3.1.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maximemaher/pyodbc#132]
```
When building v31 branch for Python 3.1.2 on Mac OS X 10.5.8, the following 
error occurs:

mkleehammer-pyodbc-3d7ddc4/src/row.cpp:337: error: invalid conversion from 
‘PyObject* (*)(PyObject*, Py_ssize_t, Py_ssize_t)’ to ‘void*’

This is due to changes in Python 3's PySequenceMethods type (e.g. see 
discussion at:

    http://www.mail-archive.com/cython-dev@codespeak.net/msg03385.html

Patch attached.
```

Original issue reported on code.google.com by `hengist....@gtempaccount.com` on 22 Oct 2010 at 3:28

Attachments:
- [row.diff](https://storage.googleapis.com/google-code-attachments/pyodbc/issue-132/comment-0/row.diff)

**Comment by GoogleCodeExporter** [comment]
Original comment by `mkleehammer` on 20 Nov 2010 at 9:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `mkleehammer` on 21 Nov 2010 at 4:46
- Added labels: **Python3**

**Comment by GoogleCodeExporter** [comment]
```
Workaround in 3.1.1-beta04

I've temporarily disabled slice assignment in Python 3 until I determine the 
correct way to port the functionality from 2 to 3.

```

Original comment by `mkleehammer` on 21 Nov 2010 at 4:58
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Where do we find this 3.1.1-beta 4?
```

Original comment by `rizw...@gmail.com` on 20 Aug 2011 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
Hi, where shall I find the pyodbc for python 3.1.4
```

Original comment by `zjczhjun...@gmail.com` on 7 Sep 2011 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
Hi, 
I uploaded a patch to issue #201 that could work as a workaround in the mean 
time.
```

Original comment by `nickl...@gmail.com` on 30 Oct 2011 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
Python 2 & 3 are now built from the same source using the 'master' branch.

```

Original comment by `mkleehammer` on 27 Dec 2011 at 12:59
- Changed state: **Complete**
